version: '3'
services:
  web:
    build: ./nginx
    container_name: "laravel-nginx"
    ports:
        - "8080:80"
    depends_on:
        - php
    volumes:
      - ./php:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./php:/src
    env_file: .env
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres
    container_name: "laravel-postgres"
    env_file: .env
    ports:
      - 5432:5432
